name: Flatter

on:
  # Rebuild once a day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/kde:5.15-22.08
      options: --privileged

    # strategy:
    #   matrix:
    #     arch: [x86_64]
    #   fail-fast: false
    #   # Only one job at a time can use the shared repository cache
    #   max-parallel: 1

    steps:
      # Checkout a repository with Flatpak manifests
      - name: Checkout
        uses: actions/checkout@v3

      # See "Multiple Architectures" below
      # - name: Setup QEMU
      #   if: ${{ matrix.arch == 'aarch64' }}
      #   id: qemu
      #   uses: docker/setup-qemu-action@v2
      #   with:
      #     platforms: arm64

      # See "GPG Signing" below
      # - name: Setup GPG
      #   id: gpg
      #   uses: crazy-max/ghaction-import-gpg@v5
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Generate a CNAME file on-the-fly for a configured host
      - name: Generate CNAME
        run: |
          echo "glaumar.github.io" > CNAME

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: |
            io.github.glaumar.v2raya_flatpak.desktop
            io.github.glaumar.v2raya_flatpak.metainfo.xml
            io.github.glaumar.v2raya_flatpak.yml
            iproute2.yml
            iptables.yml
            v2ray-core.yml
            create-v2raya-service.sh
            remove-v2raya-service.sh
            run-v2raya.sh
          arch: x86_64
          # gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: false
          upload-pages-includes: |
            CNAME
            default.css
            index.html

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
